ui/src/style/variables.less
Changed original tooltip edges to now be black and also moved a variable redundancy in variables.less (repeating border-colors)
**Old**: 
**New**:
=> UI: Tooltip edges are now black

api/src/index.ts, api/src/queries.ts, data-processing/explanations/parse_tex.py, data-processing/models/models.py, data-processing/scripts/command.py, data-processing/scripts/run_pipeline.py, data-processing/scripts/store_pipeline_log.py, data-processing/scripts/upload_citations.py, data-processing/scripts/upload_symbols.py
Sometimes, I want to create a "dev" copy of the database to test changes to the data pipeline in the UI, without impacting a clean master set of data in the dataset that everyone else is using for development and demos.
In this change, every time the data pipeline is run, it will upload data to a different schema (like a different namespace in Postgres), named by the time at which the pipeline was run (e.g., `schema_20191213_024444`). In the future, once we have validated that the data in a schema is high quality enough, it can be renamed to `public` to make it live in the UI.
This PR isn't _quite_ complete. I also want to make the schema name that data is uploaded to from the data processing scripts configurable (e.g., I can choose to always upload results to the "dev" schema). Though it …
=> Pipeline: Upload data to timestamped schemas

ui/src/ScholarReader.tsx, ui/src/ui-utils.ts
This adds code that closes the drawer if the escape key is pressed.
This felt like a nice convenience, and conveniently required very
little code.
I also revised the annotation event handler to use the same mechanism
for binding and removing events. We don't actively mount / remount
the top level `<ScholarReader />`, so there's no active motivator --
but in case we ever do it'll ensure things get added and removed properly.
=> Close the drawer on escape.

ui/src/Citation.tsx, ui/src/CitationTooltipBody.tsx, ui/src/PaperSummary.tsx, ui/src/style/citation.less, ui/src/style/paper-summary.less, ui/src/style/tooltip.less, ui/src/ui-utils.ts
This modifies the citation tooltip so that a small snippet from the
abstract id displayed. The limit I set (110 characters) is roughly
2 lines of text, which is what felt natural to me.
In doing this I ported over Semantic Scholar's text truncation
mechanism, as it tries to avoid truncating mid-word and uses the
`utf-8` ellipsis character.
=> Show a small snippet of the abstract in the citation tooltip.

ui/src/PaperSummary.tsx, ui/src/ScholarReader.tsx, ui/src/api.ts, ui/src/s2-url.ts, ui/src/state.ts, ui/src/style/paper-summary.less, ui/src/style/variables.less, ui/src/types/api.ts
The review adds functionality and api calls to S2 to fetch and modify library entries.
When signed in on S2:
* Fetches the user library entries from S2 and saves them in local storage for an hour
* Shows "In Your Library" or "Save To Library" depending on if its in your library already
* Clicking on "Save To Library" changes the button text and sends a request to add the entry to the user's library
* Clicking on "In Your Library" opens a new tab directed to the user's library in S2
When signed out:
* Clicking on the "Save To Library" button does what it does now, pops open an info box saying it isn't implemented yet. This is because we don't support sign ins from the reader at this time
This is what the reader link looks like on the S2 side for more context:
=> Save to library functionality

ui/src/Annotation.tsx, ui/src/ScholarReader.tsx, ui/src/SymbolAnnotation.tsx, ui/src/state.ts, ui/src/style/annotation.less, ui/src/style/variables.less, ui/src/types/api.ts
This is an optimization using strategies @andrewhead and I talked about to speed up symbol annotation highlighting. It now adds no perceivable costs to the annotation tooltip opening. The highlighting of in the video is just a placeholder so it's easier to see on the gif. Haven't really decided on a highlighting for the actual implementation (right now it's just the s2-influential-citation-orange but opening to suggestions.
=> Faster version of Symbol Highlights

ui/src/style/annotation.less, ui/src/style/variables.less
Description: Matching selected symbol entity now has a faint blue highlight instead of an orange underline. I didn't use hex color because hex code doesn't support transparency, I opted for RGBA color here as the variable highlight-color is using couple lines above, but it is also worth noting that there's another version of the hex color that supports alpha channel with the format AARRGGBB (which makes the hex color code 8 characters long though). 
Screenshot:
=> Changing matching symbol entity highlight to faint blue

ui/src/Drawer.tsx, ui/src/PageOverlay.tsx, ui/src/ScholarReader.tsx, ui/src/state.ts, ui/src/style/pdf-viewer.less, ui/src/types/pdfjs-viewer.ts
The PDF now moves to the side on small resolutions and will be horizontally scrollable on large resolutions. 
**edit**: It will now move a symbol into view if it would otherwise have been obscured by the side drawer.
=> Move PDF on Drawer Open

data-processing/common/parse_equation.py, data-processing/tests/mathml/relu.xml, data-processing/tests/test_parse_equation.py
Merge consecutive <mi> tags that are also direct descendants of <mrow> tags as this is a good indicator that the consecutive <mi> tags should really have been considered one word. 
**Before:**
**After:**
=> Merge Consecutive <mi> Tags

ui/src/style/annotation.less, ui/src/style/pdf-viewer.less, ui/src/style/variables.less
I used the :not() selector because we previously disabled behavior for any links with "#cite", this is just to avoid any unexpected behavior. 
All modified properties were found in the original pdf.js stylesheet, I only changed the properties that have to do with colors. 
Screenshots:
(to be compared with our custom highlights)
=> Consistent highlight between pdf.js annotation and custom annotation

ui/src/Citation.tsx, ui/src/style/tooltip.less, ui/src/style/variables.less
This catches the fatal error threw when the api fails to fetch the paper linked from the server. With this implementation, a tooltip appears even when there isn't any linked information, and the user is encouraged to provide feedback on the tooltip and (hopefully) the missing paper.
(The screenshot is made by simulating the bug... it's not an actual bug now):
=> Tooltip for citations without any linked paper

data-processing/common/models.py, data-processing/common/types.py, data-processing/config.ini, data-processing/entities/citations/commands/resolve_bibitems.py, data-processing/entities/citations/commands/upload_citations.py, data-processing/entities/citations/utils.py, data-processing/entities/symbols/commands/upload_symbols.py, data-processing/entities/symbols/types.py, data-processing/entities/symbols/utils.py, data-processing/pdf/__init__..py, data-processing/pdf/grobid_client.py, data-processing/pdf/process_pdf.py
Populate the scholar-reader database with citations and symbols from the Grobid-based PDF processing pipeline. Calls the Grobid API as a service and converts the Grobid annotations and token bounding boxes to reader entities.
Depends on [these changes](https://github.com/allenai/grobid/pull/10) to Grobid.
Had to do some mild refactoring of the existing pipeline code to enable this alternate entry point. Mostly this involves moving existing methods into different modules, like some data classes and the `upload` methods, which have been put into the `util` modules.
=> PDF Pipeline

ui/src/FindBar.tsx, ui/src/FindBarString.tsx, ui/src/FindBarSymbol.tsx, ui/src/PageOverlay.tsx, ui/src/ScholarReader.tsx, ui/src/SymbolAnnotation.tsx, ui/src/selectors/annotation.ts, ui/src/state.ts, ui/src/style/annotation.less, ui/src/style/find-bar.less
Semi-working implementation of symbol search.
**TODO:**
- Fix typescript errors
- Remove hack to clear search query on close
**Search for a symbol:**
**Interrupt a symbol search with text and vice versa:**
=> Add symbol search

.skiff/webapp.jsonnet
Add the `s2-reader.semantischolar.org` hostname to the production deployment.
=> Add additional hostname.

api/package.json
Ref https://github.com/allenai/scholar/issues/24644
Turns out it wasn't that bad, just had to dig through a bunch of documentation to find that the CLI arg still worked when using `ts-node-dev` instead of straight `node` 😄  The value of 64k comes from the online-service config, to keep it all in sync.
Tested by sending a request to the healthcheck API (/health) with a very large value in its header and witnessing the HTTP400 response, then restarting the server with the arg in place, repeating the request, and witnessing the HTTP200 response.
=> Support larger request headers in API server

.skiff/webapp.jsonnet, ingress/nginx.conf, ui/nginx.conf
Ref https://github.com/allenai/scholar/issues/24644
S2 (primarily for internal users) can use very large cookies, which often exceed default header size limits. This is a follow-up to https://github.com/allenai/scholarphi/pull/153 that increases the nginx limit to match the limit used by the API server (and, also, S2)
=> Increase request header limit for nginx

ingress/nginx.conf, ui/nginx.conf
Services on the cluster (like ScholarPhi) are only accessible
on the cluster. This means we can simply access the `X-Forwarded-For`
header from all clients.
We patched this awhile back in the [template](https://github.com/allenai/skiff-template/blob/master/proxy/nginx.conf#L14),
I figured I'd port that over to ScholarPhi too.
=> Accept the `X-Forwarded-For` header from all clients.

api/Dockerfile, ui/Dockerfile
NodeJS distributed a patch for a high severity CVE, see:
https://twitter.com/nodejs/status/1328723765157617672?s=21
I chose to bump the `node` version to `14` from `12` here because
`14` is the latest LTS release, so it seemed like a good thing
to do. Everything appeared to work, though admittedly my
testing only went as far as:
```
cd api/
docker run --rm -it 3000:3000 $(docker build -q .)
curl http://localhost:3000/health
cd ../ui
docker run --rm -it 4000:4000 $(docker build -q .)
open http://localhost:4000/?file=https://arxiv.org/pdf/0801.4750.pdf
```
Everything appeared to work. If more thorough testing is warranged
let me know (and ideally point me at instructions for doing so).
Here's the relevant ticket:
https://github.com/allenai/reviz/issues/155
Oh, and @mjlangan this CVE might …
=> Update node to patch a CVE.

.skiff/webapp.jsonnet, api/README.md, api/src/server.ts, api/src/tests/api.test.ts
This way we can use an uptime check to verify that the API is
healthy.
I removed the `livenessProbe`s, as it's something we've learned
shouldn't be used unless it's necessary.  These probes cause the
pod to be restarted when they start failing. It sounds nice in practice,
but if your server gets overwhelmed you want to give it time to
play catch-up, so that the requests being processed by the pod aren't
dropped on the floor.  The hard-restart behavior is only necessary
for pathological processes with errant behavior, like memory leaks.
=> Update the health route so it's public.

api/src/api.ts, api/src/db-connection.ts, ui/package.json, ui/src/PaperSummary.tsx, ui/src/ScholarReader.tsx, ui/src/logging.ts
There's a couple things in this PR:
1. Adds an API route at `papers/arxiv:{arxivId}/version` to return the latest version of a paper we have in the DB
2. `yarn run dev` in the /ui/ directory will start up a local version of the UI
3. The remote logger is now the default export of `logging.ts`, so it can be directly imported into files where it is needed (and we don't need to instantiate it with function calls or in a constructor or something like that). This is the same way the S2 webapp makes its client-side logger available to UI code.
4. ScholarReader component uses fat arrow functions, meaning we don't need all the `.bind(this)` goo in the constructor
5. Some tweaks to PaperSummary too. I also replaced empty element tags with `React.Fragment` to be more explicit, but this is …
=> arXiv version check API & various UI code tweaks

.gitignore, api/src/index.ts, data-processing/common/commands/database.py, data-processing/config.ini, data-processing/scripts/run_pipeline.py, ui/package-lock.json
Gathers changes to run ScholarPhi against S2 database:
1. Move all DB parameters to environment variables
2. Clean-up with try/finally when `--one-paper-at-a-time`
3. Change DB name to 'scholarphi' and use public schema as we have different DB instances for dev vs. prod
This cannot be merged yet b/c the production Skiff application probably cannot reach the DB instances in the private network (AI2 inf VPC).
=> Run ScholarPhi against S2 managed database

.github/workflows/ci.yml, api/README.md, api/bin/start_local_db.sh, api/src/tests/api.test.ts, api/src/tests/setup.ts
This does several things:
1. Adds the `./api/bin/start_local_db.sh` script for starting a local
database. It uses `docker` to run things in a container, and uses
the same Postgres version that we do now.
2. Modifies the tests to use that database.
3. Adds a CI configuration that uses GitHub actions to run the API
tests on PRs and do some light validation of the UI.
=> Run tests using a local database.

api/README.md, api/package-lock.json, api/package.json, api/src/api.ts, api/src/conf.ts, api/src/db-connection.ts, api/src/index.ts, api/src/s2-api.ts, api/src/server.ts, api/src/tests/setup.ts, api/src/types/api.ts, api/src/types/s2-api.ts, ui/src/api.ts, ui/src/papers/index.tsx, ui/src/types/api.ts
This PR started as an effort to add search, but as discussed I ended
up pausing on that change in favor of eventually using S2's regular
search API. This PR instead captures changes that I made while
implementing search that seem worth preserving.
The largest functional difference is that the API now uses an API
key when querying S2's public API. This means we can safely query
for this information in the backend when preparing papers to return
for the `/papers/list` API endpoint.
To do this I did some cleanup of the way configuration parameters
are handled so that they can be accessed in a typesafe fashion.
Lastly I cleaned up the paper list UI a bit, as it was getting
a little unruly.
=> Query S2's API using an API key if we have one + some other cleanup.

api/src/server.ts, ui/src/PrimerPage.tsx, ui/src/ScholarReader.tsx, ui/src/state.ts
Ref https://github.com/allenai/scholar/issues/25245
I reworked the part of the PrimerPage that displayed the loading indicator for entity/definition data to also indicate whether or not we've loaded citation data.
Preview:
=> Add loading indicator for citation data

data-processing/scripts/run_pipeline.py
This PR serves two purposes.
First, it disables the detection of glossary terms by the pipeline by default. This is because the glossary terms appear so often in papers, and provide such generic definitions, that I believe it will be better to disable them in our first alpha tests. Paper-specific terms and definitions (i.e., that appear within a paper, rather than in an external glossary like the Google Machine Learning Glossary) will still be extracted by default via the `definitions` entity type.
Second, it fixes buggy behavior in the pipeline arguments that filter which stages of the pipeline are run (e.g., `--entities`, `--commands`, `--start`, and `--end`. Namely, it supports:
* Default lists of entities to process that is not all entities but rather a subset (i.e., citations, …
=> Pipeline: Fix up command filters; disable glossary terms by default

data-processing/entities/definitions/commands/detect_definitions.py, data-processing/tests/test_extract_definitions.py
@nuwandavek is leading the creation of this PR to:
1. Filter out low-quality nicknames consisting mostly of other symbols
2. Detecting other types of nickanmes (e.g., ones of the form "<symbol>: <nickname>"
I will let @nuwandavek add additional clarifications here.
=> [WIP] Improve quality of definitions extracted by rule-based nickname detector

data-processing/common/commands/locate_entities.py, data-processing/common/commands/raster_pages.py, data-processing/common/compile.py, data-processing/entities/citations/commands/resolve_bibitems.py, data-processing/entities/symbols/commands/extract_symbols.py
I'm considering making updates to the pipeline to make it faster to process papers. To determine the effort required to speed up the pipeline, I'd like to collect more detailed timing information about key steps in the paper processing pipeline.
This PR adds log statements to the commands for locating entities that can be used to measure the time it takes to:
1. Insert color macros into the TeX
2. Compile the TeX
3. Raster the TeX to images
4. Difference the images
5. Locate entities in the image diffs
These steps will be performed up to thousands of times for a single paper, so strategic improvements to pipeline performance can be aided by knowing which one of these steps usually takes the longest.
Log statements are added both at the start and end of each of the steps above to make it …
=> Update pipeline log messages: remove verbose messages; add timing messages

api/src/api.ts, api/src/db-connection.ts
Use case: S2 needs a way to determine whether ScholarPhi has data for a paper in order to display a link to read said paper with ScholarPhi.
I was originally going to use the /entities endpoint, but it returns far too much data when all I need is a simple boolean response. This endpoint responds with either a `204 No Content` if the paper exists (the status code itself is the answer to the request) or `404 Not Found` if it does not exist.
=> Add API route to verify existence of a paper within ScholarPhi's DB

api/src/api.ts, api/src/server.ts
This CORS config should allow the S2 webapp (when running either in a deployed instance or on a developer laptop) to make API requests to ScholarPhi.
=> Add CORS origins so S2 webapp can hit ScholarPhi API

data-processing/config.ini
I was observing problems with the pipeline compiling TeX files that used specialized fonts (e.g., `ifsym`). It turns out that if these fonts do not already exist in the TeXLive distribution, the LaTeX compiler with automatically generate them from spec files. However, to do so, it needs to run common Unix commands like `sed` and `mkdir`. If AutoTeX does not know where to find these utilities, font generation will fail, as will compilation of that document.
Therefore, to be more robust, those who run the pipeline should edit the `texlive_bin_path` variable to also provide a search path to the common system Unix utilities.
=> Pipeline: Update default texlive_bin_path and comment in config.ini

data-processing/common/diff_images.py, data-processing/common/normalize_tex.py, data-processing/resources/01-macros.tex, data-processing/resources/03-load-color-commands.tex, data-processing/tests/test_normalize_tex.py
This PR contains two fixes:
First, the code for the pipeline commands is made robust to strange errors that arise when a paper is compiled from multiple main files (which is in fact possible for arXiv papers).
Second, the coloring macros have been made slightly more robust. To support both TeX and LaTeX, the coloring macros have conditional logic that depends on our custom macro `\scholarifdefined...`, which can be used to see what coloring commands are available in the environment, and find out other useful information.
It turns out that the way we were checking if a command was defined had the side effect of _defining_ that command to be `\relax` if it was not yet defined. In most cases, this did not matter. For the supplemental material (`supp.tex`) of paper 1712.05055, it did matter. …
=> Pipeline: Make LaTeX coloring macros and error checking more robust

data-processing/common/bounding_box.py, data-processing/common/commands/compute_iou.py, data-processing/common/file_utils.py, data-processing/common/make_digest.py, data-processing/common/models.py, data-processing/common/types.py, data-processing/entities/citations/__init__.py, data-processing/entities/citations/commands/locate_citations.py, data-processing/entities/citations/utils.py, data-processing/scripts/process.py, data-processing/tests/test_bounding_box.py
This PR introduces revives scripts for computing the accuracy of the bounding boxes extracted by the pipeline.
Of particular note, the scripts for computing bounding box accuracy were extended to handle two special cases:
1. When bounding boxes in the gold set match multiple extracted bounding boxes---in this case the box in the gold set should probably only be matched to a single extracted bounding box to not overinflate the accuracy
2. When bounding boxes in the gold set should be clustered into groups (like with sentences), and matches should be determined based on whether a group of boxes in the gold set matches a group of extracted boxes.
The main change, then, is a function called `iou_per_region`. It finds the "ideal" match between two sets of groups of bounding boxes. …
=> Update computation of bounding box detection accuracy

data-processing/common/normalize_tex.py
This PR fixes a bug in TeX file expansion.
TeX files can contain a control sequence called `\endinput` which stops TeX from continuing to read that file. This can be used, for instance, to store extra TeX at the end of a file that will not be included in the document (see another use case in this [StackExchange post](https://tex.stackexchange.com/a/23127/198728)).
Our code for expanding a TeX file that include input macros correctly handled the `\endinput` macro if it appeared in a file input from the main file of the TeX project, but it did not handle `\endinput` at all when it appeared in the main file of a TeX project. This led to a bug where `\endinput` was getting processed as an `\input` macro, and our code tried to get the arguments to it as if it was an `\input` command (which …
=> TeX: Fix bug in TeX expansion when main file ends in '\endinput'

data-processing/common/commands/locate_entities.py, data-processing/entities/citations/extractor.py, data-processing/resources/03-load-color-commands.tex, data-processing/tests/test_parse_tex.py
Several changes were needed to make the ScholarPhi pipeline robust enough to handle the [ScholarPhi paper](https://arxiv.org/abs/2009.14237). Namely:
1. A bug was found in the citation color macros where a coloring macro was calling itself recursively. That has now been fixed (`03-load-color-commands.tex`)
2. TeX logs can apparently contain non-utf-8 characters. So the logs needed to be loaded in a way that was tolerant to unexpected non-utf-8 characters (`locate_entities.tex`)
3. The bibliography entries for this paper were written idiosyncratically---often there was a newline between the `\bibitem` macro and the `{...}` curly braces in which the key for the reference was written. This was confusing our code that parsed out reference keys from the bibliography. This has since been fixed …
=> Pipeline: Several bugfixes to support ScholarPhi paper

api/package.json, api/src/api.ts, api/src/db-connection.ts, api/src/tests/api.test.ts
S2 uses this API to determine whether or not to display the Semantic Reader button on the PDP, and to prevent the button from displaying for papers that don't have any extracted entities, this change ensures we only report back with version data if we also have extracted entities for that paper.
=> Make /version API aware of entity data

ui/src/components/preview/SymbolPreview.tsx, ui/src/selectors/entity.ts
It sometimes happens that the pipeline uploads entities that have no bounding boxes at all. While most of the UI code has guards to check whether an entity has some bounding boxes before attempting to do something with those boxes, some of it does not. This leads to exceptions.
This PR introduces two small fixes in the form of guards in the UI code that check for the presence of bounding boxes for an entity before attempting to do something with those bounding boxes. In particular, the guards appear before:
1. Sorting two entities based on the position of the bounding boxes
2. Rendering a preview of a symbol
Guard #1 has been tested to fix the following exception for paper 2101.05042v1 in a local version of the UI with the fixes incorporated:
Clicking on a symbol in that paper now no …
=> UI: Add guards to sorting / display logic when an entity has no bounding boxes

ui/src/api/api.ts, ui/src/components/entity/citation/PaperSummary.tsx
The request payload of the library API on S2 now expects an array of numbers named `folders` instead of an array of strings named `tags`.
=> Fix s2 library API call

ui/src/components/entity/citation/PaperSummary.tsx, ui/src/style/paper-summary.less
Ref https://github.com/allenai/scholar/issues/26346
Also sets a minimum width on the PaperSummary component so it doesn't get too narrow.
=> Remove the "Cite" button

data-processing/common/parse_equation.py, data-processing/tests/test_parse_equation.py
Previously, the `parse_element` method took as input a MathML tree, and simultaneously cleaned the MathML tree to a normalized form _and_ extracted symbols from it at the same time.
This has been tricky to maintain. To make it easier to make a couple of upcoming changes to symbol extraction, I separated out the code for normalizing the MathML tree and exxtracting symbols from the MathML tree.
=> Clean up equation-parsing code: separate tree cleanup and symbole extraction

api/src/s2-api.ts, ui/public/papers/index.html, ui/public/viewer.html, ui/src/components/primer/PrimerPage.tsx
Ref https://github.com/allenai/scholar/issues/26407
Since "Semantic Reader" is the official name for the app, this changes some publicly-facing parts of the code to use the new name. It also makes me think we might want to rename the Slack channel while we're at it.
=> Rename ScholarPhi -> Semantic Reader in public-facing places

api/package.json, api/src/db-connection.ts, api/src/tests/api.test.ts, api/src/types/api.ts, api/src/types/validation.ts, data-processing/entities/symbols/upload.py, ui/src/api/types.ts, ui/src/components/control/EntityCreationToolbar.tsx, ui/src/components/entity/EntityAnnotationLayer.tsx
See scholar repo issue https://github.com/allenai/scholar/issues/26282
This PR includes three changes to support filtering out bounding boxes with overly large bounding boxes:
1. It detects very large bounding boxes for symbols in the pipeline scripts (`upload.py`)
2. It adds a field called `tags` to all entities that can contain arbitrary tags (in this case to support the `"large"` tag for entities with very large bounding boxes)
3. It excludes all entities with the "large" tag from being rendered in the UI. 
The detection of large bounding boxes in the `upload.py` script is an alternative to doing so with the SQL maintenance script that was first proposed in https://github.com/allenai/scholarphi-pipeline/pull/27.
=> Outlier detection

api/src/types/api.ts, api/src/types/validation.ts, data-processing/common/parse_equation.py, data-processing/common/types.py, data-processing/entities/symbols/commands/extract_symbols.py, data-processing/entities/symbols/upload.py, data-processing/tests/mathml-fragments/delta_a_d_b.xml, data-processing/tests/mathml-fragments/dot.xml, data-processing/tests/mathml-fragments/forall.xml, data-processing/tests/test_parse_equation.py, ui/src/api/types.ts, ui/src/components/control/EntityCreationToolbar.tsx, ui/src/components/entity/EntityAnnotationLayer.tsx
This PR contributes two changes.
1. Detect operator symbols (in case we eventually want to show explanations for them too)
2. Identify function symbols earlier in the pipeline---i.e., in an earlier stage in which the MathML for an equation is cleaned, rather than a later stage where that MathML is parsed for symbols. This may seem not useful, though it is a cleanup that will make it easier for me to make some other symbol segmentation improvements soon.
Because operator symbols will now be uploaded to the database, we need a way to filter them out of the UI until we decide we want to show them. Therefore, there are changes in the API and UI:
* API: extend the symbol attributes type to have a `type` field, which can be set to "identifier", "function", or "operator
* UI: only render …
=> Symbol parsing cleanup

data-processing/entities/symbols/__init__.py
Due to two on-going efforts, it is currently not useful for us to require sentences to be detected when symbols are detected.
First, we are considering swapping out the sentence-detection backend with one that does not require parsing of LaTeX.
Second, we are currently focusing on improving the pipeline's ability to detect symbols without the 'declutter' interaction, which means that sentence information is not used.
This PR decouples sentence detection from symbol detection, so that we can test out the detection of symbols in the deployed pipeline without also spending compute time on detecting sentences.
=> Pipeline: Make sentences optional for symbol detection

api/src/api.ts, api/src/db-connection.ts, api/src/tests/api.test.ts
Ref https://github.com/allenai/scholar/issues/26207
Since we might have useless on their own entities like sentences we wanted to tighten up this check we use to decide when to show the reader link on the s2 side.
=> Change entity quality check to look for citations (instead of any entity)

data-processing/common/commands/fetch_s2_data.py, data-processing/tests/common/commands/test_fetch_s2_data.py
Ref https://github.com/allenai/scholar/issues/26519
When we try to process a paper before S2 has it's references available it means the final result won't have citations processed (which are a core part of the scholarPhi value prop), in which case we won't even make the reader link available on the PDP.
This PR proposes to fail pipeline jobs where the paper's references cannot be found on the S2 public api. The short-run goal is to mark these jobs as failed so we have a more accurate picture of our overall success rate. These should happen less frequently as well now that we're delaying queuing up arxiv papers by 1 day.
Medium term we should try to communicate the error was retryable so the outside pipeline can retry the job later. @rreas I'm interested in your thoughts on that …
=> Raise exception if references not found on s2

data-processing/common/parse_equation.py, data-processing/tests/mathml-fragments/bold_relu.xml, data-processing/tests/mathml-fragments/double_bar.xml, data-processing/tests/mathml-fragments/script_x_regular_y.xml, data-processing/tests/mathml-fragments/word_sub_i.xml, data-processing/tests/test_parse_equation.py
See TODOs 2 and 11 in issue #192 on symbol segmentation.
The main issue this PR seeks to solve is one of precision extraction of complex symbols from MathML.
LaTeX symbols are detected by:
1. Extracting equations
2. Parsing those equations into MathML using KaTeX
3. Cleaning up the MathML equations
4. Visiting the elements in the MathML to find elements corresponding to symbols
The problem is that the KaTeX is sometimes a little messy. For instance the word `ReLU` is parsed into four symbols (`<mi>R</mi><mi>e</mi><mi>L</mi><mi>U</mi>`). This means that if we want ReLU to be detected as a single symbol, we need to merge together consecutive nodes into longer words.
That much has already been done. But the behavior missed a couple of corner cases. This PR addresses those corner cases. What …
=> Symbol extraction improvements: merging with scripts and font formats

data-processing/.gitignore, data-processing/common/fetch_arxiv.py, data-processing/common/unpack.py, data-processing/scripts/fetch_arxiv_sources.py
I frequently want to download and unpack the TeX sources for a single arXiv paper quickly when I am debugging issues of missing entities. The current workflow to do so requires calling a subset of the pipeline via `python scripts/run_pipeline.py --arxiv-ids <ARXIV_ID> --commands fetch-arxiv-ids` and then looking at the unpacked sources in `data/**-sources/<ARXIV_ID>`.
This was feeling a bit cumbersome, so I wrote a convenience script for fetching just a single project and unpacking it to `./tmp/<ARXIV_ID>`. The new invocation is:
```bash
python scripts/fetch_arxiv_sources.py <ARXIV_ID>
```
I am submitting for review as I would be happy to merge it to main if it was thought that this would be of general interest. That said, this might be an optimization for just one person (me) ^_^ Would …
=> Pipeline: Convenience script for fetching and unpacking sources for single arXiv ID

api/README.md, api/package-lock.json, api/package.json, api/src/api.ts, api/src/conf.ts, api/src/index.ts, api/src/tests/api.test.ts, api/src/tests/setup.ts, ui/package-lock.json, ui/package.json, ui/src/api/api.ts
Fixes https://github.com/allenai/scholar/issues/25340
After this change, calls to the 2 apis that allow directly modifying data in the db will require an access token be set in the request. I've updated the UI app so it will try to read the token from a cookie named `readerAdminToken` that people can set locally. We can share the token value in slack or something.
If directly hitting the api, the token can be set in the query string like:
`?access_token={token}`
Or via headers like:
`Authorization: Bearer {token}`
The token checking is handled by an off the shelf hapi plugin I've added to the stack called `hapi-auth-bearer-token`.
The token is stored in the skiff secrets store and can be updated there at will. When running locally a static token value of `"local"` is used.
Longer term we …
=> Use bearer token check to restrict write-apis

ui/src/ScholarReader.tsx
Fixes https://github.com/allenai/scholar/issues/26776
This PR logs the amount of time it takes to fetch all the entities/citations to heap. This will give us a helpful view on this as we make improvements.
Example request browser is making to heap with this data in it:
=> Log entity load time in heap

ui/src/style/pdf-viewer.less
Fixes https://github.com/allenai/scholar/issues/26381
This puts the native link functionality back in to the reader so things like links to other pages or internal links to headers work again.
@andrewhead I wanted to understand if there were overlapping issues you ran into before where these link annotations and our own would fight, do we need to bump these down in the z-order or something for that case or do you think this'll be okay?
Before:
Example from the [PAWLS paper](https://scholarphi.semanticscholar.org/?file=https://arxiv.org/pdf/2101.10281v1.pdf) where this links to the app aren't clickable today:
After: 
They are clickable and have a highlight hover:
=> Restore native link functionality

data-processing/scripts/run_pipeline.py
This maintains a consistent "interface" for any
calling application -- non-0 exit code represents
a failure outcome for the requested paper(s).
=> Allow unexpected errors to bubble up.

api/src/api.ts, api/src/db-connection.ts, api/src/types/validation.ts
I redid the way we extract PaperSelectors out of the route params so that we no longer have to implement a route twice to handle both arxiv and S2 IDs. For routes that only work on arxiv IDs, there's an `arxivOnlySelector` validation option that rejects S2 IDs. I also noticed some of those routes validate a correctly-shaped arxiv ID but then only use the entity ID later in the route, indicating we can simplify the API routes (or do more validation on the paper).
=> Consolidate routes that accept both types of IDs

api/src/api.ts, api/src/db-connection.ts, api/src/types/api.ts, ui/src/api/types.ts, ui/src/papers/index.tsx
Fixes https://github.com/allenai/scholar/issues/26610
As the DB size has grown, the query here to fetch all papers and their counts have started to timeout our ELB at 60s (which is also way too long to wait anyway).
Since we don't value the counts enough to improve the performance of this query in this PR I propose that we drop the counts altogether. The page now loads instantly with a list of papers that have any citation entities (which is our current bar for displaying a link on the PDP as well).
Before:
After:
=> Remove entity counts from /papers page to make it useable again

api/src/api.ts, api/src/db-connection.ts
Fixes https://github.com/allenai/scholar/issues/26728
Today this call takes ~3-4s to complete, leading to a delay in when a user might see the reader link appear and might have scrolled down the page and missed it. After this PR it takes ~300ms.
When I'd first added this citation count check I had mostly copied and pasted how the max version was being found in the /papers query which turns out to have been horrifically slow. We can instead grab the latest version directly from the `version` table which is tiny compared to the entity table.
=> Speed up version check query

data-processing/common/commands/fetch_s2_data.py, data-processing/scripts/run_pipeline.py, data-processing/tests/common/commands/test_fetch_s2_data.py
We had limited finesse in handling different classes of
errors coming back from the S2 public API.
This changeset distinguishes between the existing
4XX series errors, including API rate limiting, as well
as capturing previously unhandled error classes, such
as 5XX-series and timeouts.
The command has also been extended to allow use
of a partner API token (as-yet unfurnished), to identify
as a "partner" with less restricted rate limits (something
we're currently seeing).
=> S2 api handling

data-processing/common/commands/fetch_arxiv_sources.py, data-processing/common/fetch_arxiv.py, data-processing/scripts/run_pipeline.py, data-processing/tests/common/commands/test_fetch_arxiv_sources.py, data-processing/tests/common/test_fetch_arxiv.py
We're seeing a lot of "peer closed connection" errors when requesting
data from ArXiv. This may or may not be rate limiting; however we should
not treat it as an unrecoverable error.
This changeset does two things:
1) It intercepts expected failure modes in `fetch_from_arxiv`, raising a new error type
that can be caught in a driver script and used to provide a retryable exit code to
`scholarphi-pipeline`
2) Performs an in-process retry loop with more generous backoff delay.
This won't solve our woes but will allow us to at least retry sensibly.
=> Retry logic and retryable exit code for Arxiv fetch failures

data-processing/common/commands/base.py, data-processing/common/commands/locate_entities.py
#218 was designed to circumvent out-of-space errors by deleting the overabundance of intermediate files produced by the pipeline (paper rasters, copies of compiled TeX, etc.) when it localizes entities.
While the PR did succeed in deleting intermediate files, it failed to delete these files when there was a failure in entity detection, like a failed LaTeX compilation.
This PR fixes this issue, ensuring that the intermediate files are always deleted, regardless of whether a failure occurred for one batch of entities.
Addresses issue: https://github.com/allenai/scholar/issues/26607
=> Pipeline: Bug fix: fix deletion of intermediate files after entity batches that fail

data-processing/scripts/compute_accuracy.py
Ref https://github.com/allenai/scholar/issues/26729
This script is used to compute the accuracy of a set of bounding boxes extracted for entities.
This PR updates the accuracy computation script to ignore operator symbols when computing accuracy. Our gold (hand-labeled) datasets of bounding boxes do not include operators at this time (nor do I think they will anytime soon), though our pipeline has recently been updated to detect them. This means that precision scores take a hit and are difficult to compare to past versions of the precision score.
=> Evaluation: Fix accuracy script to ignore operator symbols

ui/public/viewer.css, ui/public/viewer.html, ui/webpack.config.js
No more green/red borders around the PDF links. This should roll out to clients without needing them to manually clear caches, too, as I've added random query param strings for cache-busting.
=> Remove link annotation borders & cache-bust viewer JS and CSS

data-processing/README.md, data-processing/common/compile.py
Add more visibility into tex related errors and update README.
Tested locally by running arxiv files containing `.tex` file and arvix files not containing `.tex` file.
=> Log warning if no .tex file is found in source dir

api/src/api.ts, api/src/db-connection.ts, api/src/types/api.ts, api/src/types/validation.ts
Opens a new endpoint to test deduplication of shared data
across instances of a given symbol.
We identify a canonical ID for each symbol, and generate a lookup
table with a single copy of data that are currently duplicated
quadratically at the DB across its instances.
This PR does not change the persistence layer itself, but
defines a desired API response payload shape, and tactically
modified the SQL we are running to build up said payload.
The endpoint can be accessed at:
`v0/papers/<id>/entities-deduped?type=all|symbol`
The response now looks like:
```json
{
"data": {
"entities": [ /* as it was minus shared data */ ],
"sharedSymbolData": {
someDisambiguatedId: {
"defining_formula_equations": [],
"defining_formulas": [],
"definition_sentences": [],
"definition_texs": [],
"definitions": …
```
=> Deduped payload

api/src/api.ts, api/src/db-connection.ts, api/src/types/api.ts, api/src/types/validation.ts, ui/src/api/types.ts
This branch changes 3 things about the current entity response:
- `source` fields are removed from entities and bounding boxes. These are sent by the UI when modifying entities, but the UI doesn't really do anything with this information besides applying a CSS style on one component (which is applied for 99% of entities).
- The entity's `version` field is similarly removed because the UI does nothing with it
- Relationships omit the `type` field because they tend to only relate to one type of thing (and it's often in the name of the relationship).
It's all behind a `slim` query param that's `false` by default so it doesn't break the UI.
In a smaller case, it's good for about 27kB savings:
`GET http://localhost:3000/api/v0/papers/arxiv:1601.00978v1/entities?type=all&slim=false` - 188.37kB …
=> Optionally omit certain fields from entity responses

api/src/api.ts
This effectively makes `entities` and `sharedSymbolData` the two top-level fields within the response and saves a couple more bytes.
=> Don't wrap the entity response with an extra field

api/src/api.ts
Good for a few kb in most cases and a solid 800kb in my worst-case example (drops from 4.4MB to 3.6MB)
=> don't return tag fields when serving deduped entities

ui/src/ScholarReader.tsx, ui/src/api/api.ts, ui/src/api/deduped.ts, ui/src/api/types.ts
This change adds an API handler for the new `entities-deduped` endpoint and a glorious un-dedupe function to make its response compatible with the existing code. Not an efficient use of memory within the browser, but it at least allows us to get the perf benefit of the new API without having to change all the UI component code.
Because `entities-deduped` is a much faster API for returning the full set of entity data, I also removed the `&showAll=true` URL param from the reader and made it always request the full set.
A couple related notes:
- With the slimmer API responses, the entities don't include their version numbers (since we only query one version at a time and these are always the same value) or sources (like 97% of these are `tex-pipeline` with a small remainder of …
=> Use the deduped entities API for loading the entities

.github/workflows/ci.yml, ui/README.md, ui/jest.config.js, ui/jest.config.ts, ui/package-lock.json, ui/package.json, ui/src/api/api.ts, ui/src/index.tsx, ui/src/utils/ui.test.ts, ui/src/utils/ui.ts
Two bugs I found recently:
1. If one is adding a query param after the PDF URL, and one fat fingers the `&`, pdf.js will ignore the garbage after the `.pdf` extension, but our code matches everything from the arXiv ID to the end of the string (e.g. `2005.06967v2.pdf?showAll=true`). This is a bug because the pdf.js viewer ignores that and properly loads the PDF, but ScholarPhi breaks with no visual indication to the user. Now the regex will correctly pull the arXiv ID out of such a URL.
2. Some math papers on arXiv have IDs that look like `math/0008020v2`. Our API puts the arXiv ID in a URL parameter, so these math IDs actually change the path the API server thinks we're requesting and returns 404 errors for those papers. I noticed we weren't encoding the URI params, so characters like `/` …
=> Fix two UI bugs and add tests

api/src/types/validation.test.ts, api/src/types/validation.ts
We have a paper with ID `math/0008020v2` in the system. Turns out, the API never had a regex to handle IDs like this. Fortunately, it also turns out that `hapi` is decoding the encoded slash for us (in the URL, this ID looks like `math%2F0008020v2` so it doesn't change the route), so we don't need to manually handle that.
=> validate math arxiv IDs

ui/src/ScholarReader.tsx, ui/src/api/api.ts
This PR addresses two issues:
1. The list of S2 paper SHAs we pass to the `getPapers` function is not deduplicated, as every instance of a paper citation is its own citation entity linking to the same SHA. The Reader API does dedupe the IDs it receives before fetching the papers from the public S2 API, but the many duplicate IDs emitted from the reader result in more requests to the Reader API being sent than are necessary.
2. If the paper has no citation entities, we never turn off the loading spinner for citations. Whoops.
As a concrete example for item 1, with the paper `https://arxiv.org/pdf/2104.01111v1.pdf`:
- Current prod code results in 8 requests to the Reader API's /papers endpoint
- This branch only makes 4 requests to the Reader API
=> Fixes around fetching citations

api/src/api.ts, ui/README.md, ui/package.json
The /papers endpoint in the reader API was adding a bunch of JSON that was being stripped out in the client. I accidentally clobbered the UI side of that with commit https://github.com/allenai/scholarphi/commit/81c0b8f40ad8fe092b45cd80f99289f162199942, which broke the display of citations in the overlays because the API response was not matching the expected shape. Of course, there were no JS errors because ScholarPhi in general returns `undefined` and happily carries on without logging anything, but that's another story.
My change here gets rid of the additional JSON in the response that was just being stripped out in the client, which gets citations working again.
=> Fix the paper API

data-processing/entities/citations/commands/resolve_bibitems.py
For a paper, we extract references from the latex and try to match them with S2's reference data. This is to add a warning if we can't match any reference. This is to get more visibility into `no_citations` error. With this, we can know whether that error is caused by scholarphi not being able to extract any reference vs being able to extract reference but can't match it.
=> Add warning if references exist, but can't match any with S2 reference data

data-processing/.dockerignore, data-processing/Dockerfile, data-processing/config.ini, data-processing/requirements.txt
https://github.com/allenai/scholar/issues/27321
Changes:
1. Use TeXLive from Arxiv instead of from `apt-get`.
2. Change config.ini to point to where TeXLive is installed
Testing: manual testing
- can compile 2 latex files that were previously failed to compile
- can compile 1 latex file that was successfully compiled
Also, the image size balloons to 18GB. We're gonna need a bigger boat, @ca16.
=> Use arxiv's compiler

ui/src/ScholarReader.tsx, ui/src/api/api.ts, ui/src/api/s2-url.ts, ui/src/components/entity/EntityAnnotationLayer.tsx, ui/src/components/entity/citation/CitationGloss.tsx, ui/src/components/entity/citation/LazyCitationGloss.tsx, ui/src/components/entity/citation/PaperSummary.tsx, ui/src/state.ts, ui/src/style/paper-summary.less
This is implemented using S2 private APIs, which we don't want to be using, so it seems like a good idea to remove it prior to getting a bunch of public eyes on the reader. I wanted to do this a separate change from my previous PR so it could be more easily reverted if we come up with a way to support this on the S2 side without needing the reader to call private APIs.
=> Remove "save to library"

ui/src/index.tsx
Per @kyleclo 's request, an optional query parameters can now 
be passed that will highlight entities that we care about manually evaluating.
Simple append one or more of the following to your URL:
```
&annotateEquations
&annotateSymbols
&annotateCitations
```
Results in things like:
=> Optional highlighting

ui/src/style/brandbar.less
Addresses #27673
The issue with padding in the brand bar for Safari seemed to be caused by the Semanti Scholar logo being rendered at a large height by default. When I hard-coded the height, the logo reappeared, and the padding issues resolved.
Here is the brand bar in Safari after the fix:
This fix was verified both in Safari and in a recent version of Chrome.
=> UI: Fix padding of brand bar in Safari

data-processing/common/parse_equation.py
This commit fixes a TypeError that was raised when certain idiomatic MathML formulas were getting parsed. The issue was that if `element.string` is called on an element that has multiple children, `None` was returned, instead of a text representation of the contents of the string.
This fix is a temporary workaround to the issue. The good thing is that the change is minimal, providing graceful degradation of behavior when something unexpected happens (i.e., when an element has multiple children). The bad thing is that this still might not be the ideal behavior; ideally, two elements should not be merged together in this function if one of them has multiple children. However, in the spirit of expedient changes that improve paper coverage without introducing new surface area for bugs, I …
=> Bugfix: fix NoneType bug in equation parser

ui/src/settings.ts
As I understand, the demo for CHI 2021 will likely not include features like equation diagrams, which expose definition information about symbols.
This PR disables equation diagrams. The end result is that equations are no longer selectable, though the symbols that they are made up of still are. So instead of having selectable equations (before):
Now readers can click on individual symbols (after):
=> UI: Disable equation diagrams

ui/src/ScholarReader.tsx, ui/src/components/entity/EntityAnnotationLayer.tsx, ui/src/components/entity/SimpleSymbolGloss.tsx, ui/src/components/primer/PrimerPage.tsx, ui/src/settings.ts
* hides primer page glossary behind
flag that is off for CHI
* hides definitional bits of the symbol
gloss behind new FF
* turns off equation diagrams using existing
FF
=> Turns off definitional features.

ui/public/viewer.html
A simple add of the skiff stats.
While I was in here though I noticed that this app already uses a analytics tracker called "Heap". I was wondering if it is desired to support them both? (Are we even still using Heap?)
=> adding skiff stats

.skiff/cloudbuild-deploy.yaml, data-processing/common/scan_tex.py, ui/src/ScholarReader.tsx, ui/src/components/control/MainControlPanel.tsx
Use of the word "master" in many technology contexts is broadly accepted to be [racist language](https://www.google.com/search?q=master+racist+language).  This change removes some of these terms in favor of "main".
=> Reduce use of 'master' language

.skiff/webapp.jsonnet
This change does two things:
1. Adds a `PodDisruptionBudget`, which tells Kubernetes that there
must always be `minAvailable` replicas up. In the case of production,
this guarantees that there will always be at least one replica to
handle incoming traffic. The main outcome of this being that
there shouldn't be downtime anymore during cluster wide Kubernetes
updates.
2. Updates the deployment specification so that Kubernetes can "surge"
while deploying changes. This makes deployments faster by quickly
deploying a full set of new replicas -- currently it does so
in a rolling fashion. This makes things a little faster, and also
ensures there's additional capacity during deploys.
=> Add a pod disruption budget, and surge during deploys.

data-processing/README.md, data-processing/entities/definitions/commands/detect_definitions.py, data-processing/entities/definitions/nlp.py, data-processing/scripts/run_pipeline.py, data-processing/tests/test_extract_definitions.py
Some attempts to run the definitions pipeline in the chi-2021-demo branch fail with 404s. It seems like the problem is access to the bucket here: `https://scholarphi.s3-us-west-1.amazonaws.com/`, where some definition-related things are stored (see data-processing/entities/definitions/nlp.py).
This PR allows one to specify an alternative base url through a command line argument when one uses `scripts/run_pipeline.py`. If an alternative is not specified, the current base url is used.
To note:
- It is assumed that what is at any alternative provided location is the same as what is in `https://scholarphi.s3-us-west-1.amazonaws.com/` now.
- This change does mean that we now expect all three desired files to be found in the same place. I _think_ this is fine for now - we can adjust if we need …
=> Pipe through definitions base url argument

ui/src/settings.ts
This PR adds a new preset to the deployed Semantic Reader UI. When deployed, this will let readers to append the `&preset=sab-2021` parameter to access symbol and abbreviation definition functionality.
None of the underlying functionality of the app is changed. The main purpose of this PR is to provide the Allen AI a switch for the Scientific Advisory board to preview experimental ML features, without turning them on for all readers of Semantic Reader.
=> Add preset for papers for 2021 SAB paper review

data-processing/entities/citations/commands/upload_citations.py, data-processing/tests/common/test_upload_entities.py
Addressing the comment [here](https://github.com/allenai/scholarphi/pull/318#issuecomment-926733871). Basically, when we write output to a given file via the `--output-forms file` option, the output is written as one json object, so `.json` fits better than `.jsonl`.
Thanks for pointing this out @andrewhead !
Testing done:
Ran the tests:
```
pytest --all
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.7.5, pytest-5.3.1, py-1.10.0, pluggy-0.13.1
rootdir: /data-processing, inifile: pytest.ini, testpaths: tests
plugins: cov-2.5.1
collected 214 items …
```
=> json instead of jsonl for output file name

ui/src/ScholarReader.tsx, ui/src/components/discourse/DiscourseControlToolbar.tsx, ui/src/components/discourse/HighlightLayer.tsx, ui/src/components/discourse/UnderlineLayer.tsx, ui/src/state.ts
In this PR, the position of the tooltip is set dynamically to be centered below the click position, right beneath the line that has been clicked.
This PR also contributes an adjustment to the tooltip show / hide behavior. In particular, updating the position of the tooltip even if the reader clicks in a different position in the sentence, and automatically dismissing the tooltip if a user clicks anywhere on a page outside of a sentence.
Some changes were made to `ScholarReader.tsx` and `state.ts` to allow the toolbar to render only once with each click event, by lightly editing the code so that a the HighlightLayer is not passed a new empty list of lead sentences every time that ScholarReader is re-rendered.
=> UI: Position tooltip for sentence right beneath click location

ui/src/style/discourse-tag.less
The tooltip previously appeared as follows. Due to its light color, it sometimes visually merged into the page behind it:
After this style change, the tooltip appears as follows. The color remains the same, though a border and shadow "pops" the tooltip off the page, making it easier to distinguish from the page it appears on.
=> UI: Add light border and shadow to tooltip to visually separate it from the text

ui/src/ScholarReader.tsx, ui/src/components/discourse/DiscoursePalette.tsx, ui/src/components/discourse/DiscourseTagChip.tsx, ui/src/components/drawer/Facets.tsx, ui/src/style/discourse-tag.less, ui/src/style/document-snippets.less
This PR contributes changes to both the functionality and the appearance of the discourse tag filters.
The first change is around the functionality. Like before, when a reader opens the drawer, they see a list of sentences belonging to all discourse categories. However, _unlike_ before, when a reader clicks on one of the tags, then _only_ that tag gets selected and all others are deselected. This behavior applies for the first tag selection only.
Then, if a reader wish to enable all tags they can click the "Everything" button, which selects all tags. If all tags are selected, the "Everything" button appears selected, and the reader can deselect all tags by clicking the "Everything" button again.
This PR also includes a few style fixes, including:
* the palette of discourse tag filters …
=> Fine-tune the behavior and appearance of discourse tag buttons

data-processing/entities/sentences/__init__.py, data-processing/entities/sentences_pdf/__init__.py, data-processing/scripts/commands.py, data-processing/scripts/run_pipeline.py
Related ticket: https://github.com/allenai/scholar/issues/31103
This issue has been resolved in this PR by moving `fetch-arxiv-pdf` step from general tex preparation to `sentence entity` command list. After the changes, the sentence pipeline will still have `fetch-arxiv-pdf`. For `citation entity`, `fetch-arxiv-pdf` step has been removed.
Example running `sentence entity`:
>python scripts/run_pipeline.py   --one-paper-at-a-time   --source arxiv   --arxiv-ids 2001.11963v1   --keep-intermediate-files   --keep-paper-data   --dry-run   --output-forms file   --output-dir outputs-1   --entities **sentences**
Command line result in pipeline order `['fetch-arxiv-sources', 'fetch-s2-metadata', 'unpack-sources', 'compile-tex', 'normalize-tex', 'compile-normalized-tex', 'raster-pages', …
=> Move fetch pdf from tex preparation pipeline to sentence pipeline

data-processing/common/types.py, data-processing/entities/citations/commands/upload_citations.py
Related to https://github.com/allenai/scholar/issues/31749.
The idea is to include the raw text we have for a bib entry in the output produced by the citations pipeline, because we might want to surface this in cases where we failed to match a bib entry to an S2 paper.
This PR adjusts the 'upload citations' command to include bib entry texts (when we have them) in the citations pipeline output, both when we write output to a db, and when we write output to a file. In the case where two bib entries have the same key, we end up with the bib entry text associated with the last one we see, and log a warning.
**NOTE:** we've also talked about including mentions linked to bib entries missing matches to S2 papers in the citations pipeline's output. That's coming up in a separate PR. This PR …
=> Add bib entry text to citations output

data-processing/entities/citations/commands/upload_citations.py
Related to https://github.com/allenai/scholar/issues/31778, builds on https://github.com/allenai/scholarphi/pull/351.
The idea is to include output for bib entries that we failed to match to S2 papers in the output of the citations pipeline, so that we can still identify the corresponding mention bounding boxes (and possible show the bib entry text n them instead).
I tested this out by running a couple of papers through (same as the ones for #351).
Output file:
[1611.07004v3-current-2.txt](https://github.com/allenai/scholarphi/files/8576617/1611.07004v3-current-2.txt)
Logs:
```
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
2022-04-27 19:19:06,158 [INFO]: The following commands will be run, in this order: ['fetch-arxiv-sources', …
```
=> Include bib entries with no s2 paper matches in citations output

data-processing/requirements.txt
When I tried running the tests off the chi-2021-demo branch in a newly built image, I saw errors like this:
```
...
tests/test_extract_definitions.py:7: in <module>
from entities.definitions.commands.detect_definitions import (
entities/definitions/__init__.py:13: in <module>
from .commands.detect_definitions import DetectDefinitions
entities/definitions/commands/detect_definitions.py:16: in <module>
from ..nlp import DefinitionDetectionModel
entities/definitions/nlp.py:12: in <module>
from transformers import (CONFIG_MAPPING, AutoConfig, AutoTokenizer,
/usr/local/lib/python3.7/dist-packages/transformers/__init__.py:345: in <module>
from .trainer import Trainer, set_seed, torch_distributed_zero_first, EvalPrediction
/usr/local/lib/python3.7/dist-packages/transformers/trainer.py:64: in …
```
=> pin wandb to 0.12.18

data-processing/common/types.py, data-processing/common/upload_entities.py, data-processing/entities/citations/commands/upload_citations.py, data-processing/tests/common/test_upload_entities.py
Related to https://github.com/allenai/scholar/issues/32733, and https://github.com/allenai/scholar/issues/32730.
This PR adjusts the code that saves citation items to include, for each reference, a representation of it independent of its inline mentions (if any). This allows us to have some representation of references that we have no inline mentions for, which is the goal.
I've made it so that these additional items are only saved in the file version of the output, not in the scholarphi DB too, because:
a) We want this extra info for the new reader, and the new reader only looks in the file version of the output.
b) I think confirming that it does not adversely affect things using the db version of the output would be a non-trivial amount  more work than doing the relevant part of what's …
=> Pipe through mentionless bibs

api/src/s2-api.ts, data-processing/common/commands/fetch_s2_data.py, data-processing/tests/common/commands/test_fetch_s2_data.py
* Parent task = [Switch scholarphi to new public API endpoint #32158](https://github.com/allenai/scholar/issues/32158#top)
* As seen in [comment/question](https://github.com/allenai/scholar/issues/32158#issuecomment-1456799584), we have 2 goals:
* GOAL 1 = use the latest `graph/v1/` endpoint instead of legacy `v1/` endpoint
* GOAL 2 = use the regular `api.semanticscholar.org` subdomain, instead of an optional `partner.semanticscholar.org` subdomain.
* Question: before, users with `S2_PARTNER_API_TOKEN` env were calling the partner domain for higher rate limit.  Can we use the same token on the regular `api.semantic.org` subdomain?   
* [Rodney says yes](https://github.com/allenai/scholar/issues/32158#issuecomment-1487492642).
* THIS PR is for the `main` branch.
* Goal 1 was done in the …
=> Switch to new public API endpoint, and deprecate partner subdomain

api/src/s2-api.ts, data-processing/common/commands/fetch_s2_data.py, data-processing/tests/common/commands/test_fetch_s2_data.py
* Parent task = [Switch scholarphi to new public API endpoint #32158](https://github.com/allenai/scholar/issues/32158#top)
* As seen in [comment/question](https://github.com/allenai/scholar/issues/32158#issuecomment-1456799584), we have 2 goals:
* GOAL 1 = use the latest `graph/v1/` endpoint instead of legacy `v1/` endpoint
* GOAL 2 = use the regular `api.semanticscholar.org` subdomain, instead of an optional `partner.semanticscholar.org` subdomain.
* Question: before, users with `S2_PARTNER_API_TOKEN` env were calling the partner domain for higher rate limit.  Can we use the same token on the regular `api.semantic.org` subdomain?   
* [Rodney says yes](https://github.com/allenai/scholar/issues/32158#issuecomment-1487492642).
* THIS PR is for the `chi-2021-demo` branch.
* Goal 1 is …
=> Deprecate partner subdomain
